#!/bin/bash
set -euo pipefail

root="$(dirname "$(readlink -f "$0")")/.."
if [[ "${1:-}" != "run" ]]; then
	exec "${root}/bin/golangci-lint" "$@"
fi

(cd "$root" && "${root}/bin/bit" -q custom-gcl)
exec "${root}/dist/devel/custom-gcl" "$@"
